name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.github.io
baseurl: /ph-submissions
permalink: :categories/:title
exclude:
  - deprecated
  - vendor
  - Gemfile
  - Gemfile.lock
highlighter: rouge
markdown: kramdown
permalink: :categories/:title
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "es"
    values:
      lang: "es"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
  -
    scope:
      path: "lessons"
    values:
      lesson: true
  -
    scope:
      path: "lessons/deprecated"
    values:
      lesson: false
  -
    scope:
      path: "es/lecciones"
    values:
      lesson: true
  -
    scope:
      path: "fr/lecons"
    values:
      lesson: true
  -
    scope:
      path: _posts
    values:
      category: posts

# For local work: bundle exec jekyll serve --watch --baseurl '/proghistdev' or wherever else your local site is located

theme: jekyll-theme-minimal